server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/novelnook?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#下面这个，启用后PatronController.java里面注释掉的那一段，可以正常解析MVC视图，在IDEA里也能跳转，但是启动后访问localhost:8080/patron/all不行
#  mvc:
#    view:
#      prefix: classpath:/static/
#      suffix: .html
